About
Lisnyi/team-project pull request #9
Opened 2022-05-13 15:16 UTC by Olek9508

убрал разметку html and css в секции гарантии, так как были добавлены туда ошибочно

2022-05-13 15:24 UTC, Lisnyi requested changes

2022-05-13 15:24 UTC, Lisnyi commented on src/partials/about.html
> +      <h1 class="about__title">Teacher</h1>
h1 тільки в Герої, заміни на h2

2022-05-13 15:24 UTC, Lisnyi commented on src/partials/about.html
> +    <a href="" lang="en" class="teacher__link">Cambrige English Entry Level Certificate</a>
Прибери lang, в нас на сайт заданий lang="en"

2022-05-13 15:24 UTC, Lisnyi commented on src/sass/layout/_about.scss
> +letter-spacing: 0.08em;
letter-spacing: 0.08em прибери в нас задано на body

2022-05-13 16:53 UTC, Lisnyi requested changes
Кольори задай через змінні, вони вже прописані

2022-05-13 17:43 UTC, Olek9508 commented on src/partials/about.html
> +      <h1 class="about__title">Teacher</h1>
done

2022-05-13 17:43 UTC, Olek9508 commented on src/partials/about.html
> +    <a href="" lang="en" class="teacher__link">Cambrige English Entry Level Certificate</a>
done

2022-05-13 17:43 UTC, Olek9508 commented on src/sass/layout/_about.scss
> +letter-spacing: 0.08em;
done

2022-05-13 17:44 UTC, Olek9508 commented on src/sass/layout/_about.scss
> +font-size: 14px;
done

2022-05-13 19:35 UTC, Lisnyi requested changes

2022-05-13 19:35 UTC, Lisnyi commented on src/sass/layout/_about.scss
> +color: #FF6B09;
кольори через "var"

2022-05-13 22:44 UTC, Olek9508 commented on src/sass/layout/_about.scss
> +color: #FF6B09;
добре, зранку вишлю )

2022-05-14 07:49 UTC, Lisnyi approved these changes

2022-05-14 07:50 UTC, Olek9508 commented on src/sass/layout/_about.scss
> +color: #FF6B09;
відправив)

2022-05-14 07:50 UTC, merged